// <auto-generated />
using System;
using ExamBuilder.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamBuilder.DAL.Migrations
{
    [DbContext(typeof(ExamBuilderDbContext))]
    [Migration("20260313132103_ChangeBookInformation")]
    partial class ChangeBookInformation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamBuilder.DAL.Entities.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GradeInfo")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.DescriptiveQuestion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DifficultyLevelID")
                        .HasColumnType("int");

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.HasIndex("DifficultyLevelID");

                    b.HasIndex("LessonID");

                    b.ToTable("DescriptiveQuestions");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.DifficultyLevel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.ToTable("DifficultyLevels");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Title = "آسان"
                        },
                        new
                        {
                            ID = 2,
                            Title = "متوسط"
                        },
                        new
                        {
                            ID = 3,
                            Title = "سخت"
                        });
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.ExceptionLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ExceptionLogs");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.FillInBlankItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("FillInBlankQuestionID")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.HasIndex("FillInBlankQuestionID");

                    b.ToTable("FillInBlankItems");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.FillInBlankQuestion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DifficultyLevelID")
                        .HasColumnType("int");

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.HasIndex("DifficultyLevelID");

                    b.HasIndex("LessonID");

                    b.ToTable("FillInBlankQuestions");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.Lesson", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("LessonCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.HasIndex("BookID");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.MatchingItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("LeftText")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MatchingQuestionID")
                        .HasColumnType("int");

                    b.Property<string>("RightText")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.HasIndex("MatchingQuestionID");

                    b.ToTable("MatchingItems");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.MatchingQuestion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DifficultyLevelID")
                        .HasColumnType("int");

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.HasIndex("DifficultyLevelID");

                    b.HasIndex("LessonID");

                    b.ToTable("MatchingQuestions");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.OptionalQuestion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DifficultyLevelID")
                        .HasColumnType("int");

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<string>("Option1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Option2")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("Option3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Option4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.HasIndex("DifficultyLevelID");

                    b.HasIndex("LessonID");

                    b.ToTable("OptionalQuestions");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.ShortQuestion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DifficultyLevelID")
                        .HasColumnType("int");

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.HasIndex("DifficultyLevelID");

                    b.HasIndex("LessonID");

                    b.ToTable("ShortQuestions");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.TrueFalseItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrueFalseQuestionID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TrueFalseQuestionID");

                    b.ToTable("TrueFalseItems");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.TrueFalseQuestion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DifficultyLevelID")
                        .HasColumnType("int");

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.HasIndex("DifficultyLevelID");

                    b.HasIndex("LessonID");

                    b.ToTable("TrueFalseQuestions");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.DescriptiveQuestion", b =>
                {
                    b.HasOne("ExamBuilder.DAL.Entities.DifficultyLevel", "DifficultyLevel")
                        .WithMany("DescriptiveQuestions")
                        .HasForeignKey("DifficultyLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamBuilder.DAL.Entities.Lesson", "Lesson")
                        .WithMany("DescriptiveQuestions")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DifficultyLevel");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.FillInBlankItem", b =>
                {
                    b.HasOne("ExamBuilder.DAL.Entities.FillInBlankQuestion", "FillInBlankQuestion")
                        .WithMany("Items")
                        .HasForeignKey("FillInBlankQuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FillInBlankQuestion");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.FillInBlankQuestion", b =>
                {
                    b.HasOne("ExamBuilder.DAL.Entities.DifficultyLevel", "DifficultyLevel")
                        .WithMany("FillInBlankQuestions")
                        .HasForeignKey("DifficultyLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamBuilder.DAL.Entities.Lesson", "Lesson")
                        .WithMany("FillInBlankQuestions")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DifficultyLevel");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.Lesson", b =>
                {
                    b.HasOne("ExamBuilder.DAL.Entities.Book", "Book")
                        .WithMany("Lessons")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.MatchingItem", b =>
                {
                    b.HasOne("ExamBuilder.DAL.Entities.MatchingQuestion", "MatchingQuestion")
                        .WithMany("Items")
                        .HasForeignKey("MatchingQuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchingQuestion");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.MatchingQuestion", b =>
                {
                    b.HasOne("ExamBuilder.DAL.Entities.DifficultyLevel", "DifficultyLevel")
                        .WithMany("MatchingQuestions")
                        .HasForeignKey("DifficultyLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamBuilder.DAL.Entities.Lesson", "Lesson")
                        .WithMany("MatchingQuestions")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DifficultyLevel");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.OptionalQuestion", b =>
                {
                    b.HasOne("ExamBuilder.DAL.Entities.DifficultyLevel", "DifficultyLevel")
                        .WithMany("OptionalQuestions")
                        .HasForeignKey("DifficultyLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamBuilder.DAL.Entities.Lesson", "Lesson")
                        .WithMany("OptionalQuestions")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DifficultyLevel");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.ShortQuestion", b =>
                {
                    b.HasOne("ExamBuilder.DAL.Entities.DifficultyLevel", "DifficultyLevel")
                        .WithMany("ShortQuestions")
                        .HasForeignKey("DifficultyLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamBuilder.DAL.Entities.Lesson", "Lesson")
                        .WithMany("ShortQuestions")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DifficultyLevel");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.TrueFalseItem", b =>
                {
                    b.HasOne("ExamBuilder.DAL.Entities.TrueFalseQuestion", "TrueFalseQuestion")
                        .WithMany("Items")
                        .HasForeignKey("TrueFalseQuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrueFalseQuestion");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.TrueFalseQuestion", b =>
                {
                    b.HasOne("ExamBuilder.DAL.Entities.DifficultyLevel", "DifficultyLevel")
                        .WithMany("TrueFalseQuestions")
                        .HasForeignKey("DifficultyLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamBuilder.DAL.Entities.Lesson", "Lesson")
                        .WithMany("TrueFalseQuestions")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DifficultyLevel");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.Book", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.DifficultyLevel", b =>
                {
                    b.Navigation("DescriptiveQuestions");

                    b.Navigation("FillInBlankQuestions");

                    b.Navigation("MatchingQuestions");

                    b.Navigation("OptionalQuestions");

                    b.Navigation("ShortQuestions");

                    b.Navigation("TrueFalseQuestions");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.FillInBlankQuestion", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.Lesson", b =>
                {
                    b.Navigation("DescriptiveQuestions");

                    b.Navigation("FillInBlankQuestions");

                    b.Navigation("MatchingQuestions");

                    b.Navigation("OptionalQuestions");

                    b.Navigation("ShortQuestions");

                    b.Navigation("TrueFalseQuestions");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.MatchingQuestion", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ExamBuilder.DAL.Entities.TrueFalseQuestion", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
